### ISSUE TITLE
Don't use Qt?

### ISSUE THREAD

**Issue by ddulic** [jumpnow/meta-rpi#5]
Possible to easily build an image without using qt?

Thanks.

**Comment by scottellis** [comment]
Yes. Try the console-image

  https://github.com/jumpnow/meta-rpi/blob/morty/images/console-image.bb

But even that image is pretty bloated. It's just a demo.

Another more minimal example is the audio-image recipe

  https://github.com/jumpnow/meta-rpi/blob/morty/images/audio-image.bb

This is a custom image for the Pandora player in my office. I'm pretty
sure I'm the only one who uses it.

But that's what Yocto is good for, making custom O/S images that only
contain what you need.

I run this system pretty much all day everyday.

"Damir Dulic" <notifications@github.com> said:

**Comment by ddulic** [comment]
Thanks for the fast answer! Still learning how yocto works. Any tips on a general guide or tutorial other then the documentations which is endless?

Thanks once again :)

**Comment by scottellis** [comment]
Other then the stuff on my site ? ;-)

  http://jumpnowtek.com/

The docs from my site come from stuff I've written up for customers
over the years for different projects. It is geared toward new users,
though typically experienced software types that are only new to Yocto.

I pretty much stick to the Yocto documentation or look for examples
in the meta-layers from the Yocto and OE projects.

The Yocto project moves pretty fast so things are always changing.

If you are serious about using Yocto, my biggest recommendation is a
fast build machine, otherwise you spend too much time waiting between
iterations when experimenting.


"Damir Dulic" <notifications@github.com> said:
